server {
    listen 80;
    server_name example.com;

    root /usr/share/nginx/html;
    index index.html;

    # Enable SSI to parse time/date commands in files
    ssi on;

    location / {
        try_files $uri $uri/ =404;
    }
}